spring:
  application:
    name: onboarding
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/onboarding_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace