spring:
  application:
    name: Onboarding
  datasource:
    url: jdbc:mysql://localhost:3306/onboarding
    username: root
    password: Rlatpdus0917!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace